### DISCUSSION TITLE
Meine Beispiele: Maximale Batteriekapazität, Solarproduktion einzelner Tracker und historische Monatsdaten

### DISCUSSION THREAD

**Discussion by mce2024** [spali/go-rscp#65] [Show and tell]
Hallo allerseits,
als Neuling habe ich mich in den letzten Tagen mit diesem genialen Tool in Kombination mit Homeassistant und Grafana auseinandergesetzt. Mein Ziel war, ein paar Spezialdaten in die Langzeitanalyse zu bekommen. Hiermit möchte ich meine Ergebnisse der Community zur Verfügung stellen. Vielleicht können ja andere von meinen Ergebnissen profitieren und schneller zu ihrem Ziel kommen.

**Beispiel 1: Maximale Batteriekapazität**
Mein S10X Compact verfügt über 4 Batterien (DCB0-3). Deren max. nutzbare Kapazität wird über die Jahre nachlassen. Um diesen Prozess zu verfolgen, lese ich die Werte wie folgt aus:

Meine Datei "e3dc_dcb0.json" lautet:
```json
[
  [
    "BAT_REQ_DATA",
    [
      ["BAT_INDEX", "Uint16", 0],
      ["BAT_REQ_DCB_INFO", "Uint16", 0]
    ]
  ]
]
```
Hierbei bezeichnet die "0" als Parameter von BAT_REQ_DCB_INFO die Batterie ID. D.h. für die anderen drei Batterien habe ich jeweils auch so eine JSON-Datei erzeugt, die dann die entsprechende Identifikationsnummer (0-3) beinhaltet.

Da die Kapazitätsinformationen im Ergebnis etwas verschachtelt dargestellt werden, muss ich im Shell.Script mit "[].BAT_DCB_INFO" entsprechend tiefer einsteigen.

Meine Datei "e3dc_dcb0.sh" lautet:
```shell
#!/bin/sh
set -e
export PATH=/config/bin:$PATH
cd "$(dirname $0)"

e3dc -file ./e3dc_dcb0.json | jq -cM '{ "result": .[].BAT_DCB_INFO }'
```

Ich habe auch eine solches Shell-Skript für jede Batterie individuell angelegt, da ich sonst die einzelnen Werte nicht unterschieden bekommen. D.h. im Homeassistant habe ich dann auch pro Batterie einen Command Line Sensor, dessen Wert dann an einen individuellen Sensor pro Batterie übergeben wird.

Meine Datei "e3dc.yaml" lautet für diese Einträge:
```yaml
command_line:
  - sensor:
      name: e3dc_dcb0
      command: "/config/packages/e3dc/e3dc_dcb0.sh"
      command_timeout: 1
      scan_interval: 86400
      json_attributes:
        - result
      value_template: "OK"

sensor:
  - platform: template
    sensors:
      e3dc_dcb0_full_charge_capacity:
        friendly_name: Maximale Kapazität DCB0
        device_class: energy
        value_template: "{{ state_attr('sensor.e3dc_dcb0', 'result')['BAT_DCB_FULL_CHARGE_CAPACITY'] }}"
        unit_of_measurement: Ah
```

**Beispiel 2: Solarproduktion einzelner Tracker**
Hierbei war es zunächst etwas knifflig, die richtigen Variablen herauszufinden. Da ich über zwei Strings bzw. Tracker verfüge, musste ich ähnlich wie im Beispiel 1 jeweils eine JSON-Datei und ein individuelles Shell-Skript erstellen, um die Werte in Homeassistant unterschiedlich einbinden zu können.

Meine Datei "e3dc_tracker1.json" lautet:
```json
[
  [
    "PVI_REQ_DATA",
    [
      ["PVI_INDEX", "Uint16", 0],
      ["PVI_REQ_DC_POWER", "Uint16", 0],
      ["PVI_REQ_DC_VOLTAGE", "Uint16", 0],
      ["PVI_REQ_DC_CURRENT", "Uint16", 0],
      ["PVI_REQ_DC_STRING_ENERGY_ALL", "Uint16", 0]
    ]
  ]
]
```
Hier sind es die "0" in jeder "PVI_REQ..."-Zeile, die ich für die entsprechende Datei des zweiten Trackers auf "1" anpassen musste, um dessen Werte zu erhalten. (Die "0" bei "PVI_INDEX" bleibt!)

Mein Shell-Skript "e3dc_tracker1.sh" für den ersten Tracker lautet:
```shell
#!/bin/sh
set -e
export PATH=/config/bin:$PATH
cd "$(dirname $0)"

e3dc -file ./e3dc_tracker1.json | jq -cM '{ "result": .[].PVI_DC_POWER }'
```

In der Datei "e3dc.yaml" lautet das dann:
```yaml
command_line:
  - sensor:
      name: e3dc_get_tracker1
      command: "/config/packages/e3dc/e3dc_tracker1.sh"
      command_timeout: 1
      scan_interval: 10
      json_attributes:
        - result
      value_template: "OK"

sensor:
  - platform: template
    sensors:
      e3dc_tracker1:
        friendly_name: Solarproduktion-Tracker 1
        device_class: power
        value_template: "{{ state_attr('sensor.e3dc_get_tracker1', 'result')['PVI_VALUE'] }}"
        unit_of_measurement: W
```

**Beispiel 3: historische Monatsdaten**
Ebenfalls zur Langzeitanalyse möchte ich mir die "offizielle" Monatswerte des E3DC-Geräts darstellen und abspeichern lassen.

Dafür muss ich mir erstmal eine JSON-Datei erzeugen. Meine Datei "historical_lastmonth.jd" reduziert sich dabei auf Folgendes:
```jq
(
  now as $now |
  # apply local timezone diff to utc time
  def fixTimezone: . | (
    . -= (0|strflocaltime("%H") | tonumber) * 3600 |
    . -= (0|strflocaltime("%M") | tonumber) * 60
  );
  # returns the timespan the given amount of days as timestamp (seconds)
  def timespanDay(days): . | (
    . = (24 * 60 * 60 * days)
  );
  # returns the start of the day of the given date as timestamp
  def startOfDay: . | (
    . = if . == null then $now else . end |
    gmtime | [.[0],.[1],.[2],0,0,0,0,0] | mktime
  );
  # returns the start of the month of the given date as timestamp
  def startOfMonth: . | (
    . = if . == null then $now else . end |
    gmtime | [.[0],.[1],1,0,0,0,0,0] | mktime
  );
  # returns the last day of the month (or number of days in the month) from the given date
  def daysInMonth: . | (
    . = if . == null then $now else . end |
    (. | gmtime | .[2] = 28 | mktime | . += timespanDay(4)) as $next_month |
    $next_month - timespanDay($next_month | gmtime | .[2]) | gmtime | .[2]
  );
  # returns the start of the year from the given date as timestamp
  def startOfYear: . | (
    . = if . == null then $now else . end |
    gmtime | [.[0],0,1,0,0,0,0,0] | mktime
  );
  # returns the last day of the year (or number of days in the year) from the given date
  def daysInYear: . | (
    . = if . == null then $now else . end |
    gmtime | [.[0],11,31,0,0,0,0,0] | mktime | strftime("%j") | tonumber
  );
  . =
[
  [ # month before
    "DB_REQ_HISTORY_DATA_MONTH",
    [
      ["DB_REQ_HISTORY_TIME_START", ( . = (startOfMonth - timespanDay(1)) | startOfMonth | fixTimezone | todateiso8601 )],
      ["DB_REQ_HISTORY_TIME_INTERVAL", ( . = timespanDay((startOfMonth - timespanDay(1)) | startOfMonth | daysInMonth) | todateiso8601 )],
      ["DB_REQ_HISTORY_TIME_SPAN",     ( . = timespanDay((startOfMonth - timespanDay(1)) | startOfMonth | daysInMonth) | todateiso8601 )]
    ]
  ]
]
)
```

Im Shell-Skript erzeuge ich dann erstmal mit dieser .jd-Datei ein JSON-File, das ich dann anschließend mit dem "e2dc"-Kommando einlese.
Meine Datei "e3dc_lastmonth.sh" lautet: 
```shell
#!/bin/sh
set -e
export PATH=/config/bin:$PATH
cd "$(dirname $0)"

jq -ncM "$(cat ./historical_lastmonth.jd)" >historical_lastmonth.json
e3dc -file historical_lastmonth.json | jq -cM '{ "result": .[].DB_SUM_CONTAINER }'
```

In der "e3dc.yaml" nutze ich das dann wie folgt:
```yaml
command_line:
  - sensor:
      name: e3dc_lastmonth
      command: "/config/packages/e3dc/e3dc_lastmonth.sh"
      command_timeout: 1
      scan_interval: 86400
      json_attributes:
        - result
      value_template: "OK"

sensor:
  - platform: template
    sensors:
      e3dc_db_bat_power_in_lm:
        friendly_name: Batterie Laden (letzter Monat)
        device_class: energy
        value_template: "{{ state_attr('sensor.e3dc_lastmonth', 'result')['DB_BAT_POWER_IN'] }}"
        unit_of_measurement: Wh
      e3dc_db_bat_power_out_lm:
        friendly_name: Batterie Entladen (letzter Monat)
        device_class: energy
        value_template: "{{ state_attr('sensor.e3dc_lastmonth', 'result')['DB_BAT_POWER_OUT'] }}"
        unit_of_measurement: Wh
      e3dc_db_dc_power_lm:
        friendly_name: Solarproduktion (letzter Monat)
        device_class: energy
        value_template: "{{ state_attr('sensor.e3dc_lastmonth', 'result')['DB_DC_POWER'] }}"
        unit_of_measurement: Wh
      e3dc_db_grid_power_in_lm:
        friendly_name: Netzeinspeisung (letzter Monat)
        device_class: energy
        value_template: "{{ state_attr('sensor.e3dc_lastmonth', 'result')['DB_GRID_POWER_IN'] }}"
        unit_of_measurement: Wh
      e3dc_db_grid_power_out_lm:
        friendly_name: Netzbezug (letzter Monat)
        device_class: energy
        value_template: "{{ state_attr('sensor.e3dc_lastmonth', 'result')['DB_GRID_POWER_OUT'] }}"
        unit_of_measurement: Wh
```

Ich hoffe meine Beispiele sind verständlich und für den Ein oder Anderen hilfreich, wenn er ebenfalls etwas tiefer in die Daten reingreifen möchte. Leider habe ich keinen Weg gefunden, das hier besser zu formatieren. Bin, wie gesagt, noch neu hier. Habe es immer versucht, als "Code" einzufügen.

Viel Spaß und Erfolg mit den Beispielen! "Go-RSCP" ist ein wirklich tolles kleines Projekt!
